### ISSUE TITLE
Missing auxiliary field

### ISSUE THREAD

**Issue by chilampoon** [hasindu2008/slow5tools#77]
Hello there, I am using pyslow5 for my task and I found there's one column called `"end_reason"` in my slow5 file, but I couldn't access it.  
It is not in the keys of `s5.seq_reads(aux = 'all')` or `s5_data = s5.seq_reads(aux = ["start_time", "read_number", "start_mux", "median_before", "end_reason", "channel_number"])`...

**Comment by Psy-Fer** [comment]
Hello,

End_reason has been a mess on the ONT side, where they have changed its type multiple times between versions of fast5, as well as their own tools breaking the field. I left it out for now until it was sorted out (which it is, with ONT devs).

Also slow5tools is ignoring this field too for the same reason. Is there a reason you need this field?

**Comment by chilampoon** [comment]
Ah I see, thanks for the explanation! 
Yep I wrote a new slow5 file, then added my old slow5 header to that new file, then used slow5tools. Missing that end_reason field caused errors for viewing, but then I manually changed the header, `slow5tools view` works well. Also I hope there's the writing functionality like pysam write.. (maybe it exists I just didn't find it)

**Comment by Psy-Fer** [comment]
We are currently testing the latest pyslow5 build before release.

If you want to give it a go, you can checkout the pywrite branch.

I have added writing, appending and multithreading (on the C side) for writing, sequential and random access reading. I've also sped a lot of the underlying hits up by a lot. Be aware, it's still in testing, so there may be bugs, so use at your own curiosity 😄

**Comment by chilampoon** [comment]
> We are currently testing the latest pyslow5 build before release.
> 
> If you want to give it a go, you can checkout the pywrite branch.
> 
> I have added writing, appending and multithreading (on the C side) for writing, sequential and random access reading. I've also sped a lot of the underlying bits up by a lot and fixed a few memory leaks. Be aware, it's still in testing, so there may be bugs, so use at your own curiosity 😄

Sure, I'll give it a try!
