### ISSUE TITLE
SLOW5 files not working with nanopolish polyA

### ISSUE THREAD

**Issue by maximus-sci** [hasindu2008/slow5tools#78]
Hello I'm unable to use slow5 files for polyA calling and was hoping you could help.

I can successfully convert my fast5 files into slow5 and then merge them together using slow5tools.
Indexing with nanopolish also executes with no errors.

When I try to call polyA tail lengths, the script runs with no errors and produces this output:
`$nanopolish polya --reads .merged.fastq.gz --bam merged.sorted.bam --genome Reference.cdna.all.fa.bgzf > polyA.tsv`
`[post-run summary] total reads: 28975, unparseable: 0, qc fail: 365, could not calibrate: 524, no alignment: 56, bad fast5: 0`

but in the tsv file, every single read has the qc tag "READ_FAILED_LOAD"

When I try to get tail lengths without converting to slow5, many/most of the reads have the qc tag PASS.
Any advice?

**Comment by hasindu2008** [comment]
Could you please put the commands you used to convert to blow5 and then the nanopolish commands for using blow5?

**Comment by hasindu2008** [comment]
@maximus-sci 
I think I found the issue and applied a fix which you can find the instructions here https://github.com/jts/nanopolish/issues/967
