### ISSUE TITLE
Bad fast5 attribute pore type

### ISSUE THREAD

**Issue by mbhall88** [hasindu2008/slow5tools#85]
I got this error when using `f2s` in v0.6.0.

```
Bad fast5: Attribute read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20/pore_type in /nfs/research/zi/mbhall/tech_wars/data/madagascar/nanopore/raw_data/md_tb_reseq_2019_5/multi_fast5s/BC76_r0b1235_0.fast5 is duplicated and has two different values in two different places. Please report this with an example FAST5 file at 'https://github.com/hasindu2008/slow5tools/issues' for us to investigate.
```

Here is the fast5 that caused it.
[BC76_r0b1235_0.fast5.gz](https://github.com/hasindu2008/slow5tools/files/9642784/BC76_r0b1235_0.fast5.gz)

**Comment by hasindu2008** [comment]
Hi @mbhall88 
Is this a very recently generated FAST5 file?
@hiruna72 can you have a look at this attached file please?

**Comment by Psy-Fer** [comment]
interesting!

So i had a quick look at this with h5py

If you do something like this:

```python3
import h5py

f = h5py.File('BC76_r0b1235_0.fast5', 'r')

for read in f:
    for i, j in f[read].attrs.items():
        print(read, i, j)
```

you get something like...
```
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type b'not_set'
read_001526db-9526-4bc7-9e76-00f4259392cc run_id b'e7c896467265d9c5a774efee85e670ff7a21a05d'
read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20 pore_type b'not_set'
read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20 run_id b'e7c896467265d9c5a774efee85e670ff7a21a05d'
read_00b22781-bc8f-441a-a7c9-de8dcc597c59 pore_type b'not_set'
read_00b22781-bc8f-441a-a7c9-de8dcc597c59 run_id b'e7c896467265d9c5a774efee85e670ff7a21a05d'
read_01b85d51-168b-42c7-afaa-fce73c24f47f pore_type b'not_set'
read_01b85d51-168b-42c7-afaa-fce73c24f47f run_id b'e7c896467265d9c5a774efee85e670ff7a21a05d'
read_020f7362-e31b-46c6-8e4d-70b08a6f2c43 pore_type b'not_set'
read_020f7362-e31b-46c6-8e4d-70b08a6f2c43 run_id b'e7c896467265d9c5a774efee85e670ff7a21a05d'
read_032ba99a-a786-4c96-a962-a589588da4c2 pore_type b'not_set'
...
```


But if I look at the actual values...

```python3
for read in f:
    for i in f[read].attrs['pore_type']:
        print(read,'pore_type:', i)
```

I can see this

```
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 110
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 111
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 116
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 95
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 115
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 101
read_001526db-9526-4bc7-9e76-00f4259392cc pore_type: 116
read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20 pore_type: 110
read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20 pore_type: 111
read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20 pore_type: 116
read_008c8f1f-f32f-4b23-ab6f-1ef4f4531a20 pore_type: 95
...
```

This is hilarious. @hasindu2008 what do you wanna do?


James

**Comment by Psy-Fer** [comment]
Okay a few more details.

```python3
for read in f:
    for i, j in f[read].attrs.items():
        print(read, i, type(j))
```

gives:

```        
read_fec54356-9a3a-42c3-9e8f-739513a3619b pore_type <class 'numpy.bytes_'>
read_fec54356-9a3a-42c3-9e8f-739513a3619b run_id <class 'numpy.bytes_'>
read_feec9e55-5765-4440-a414-0b624ac0d3aa pore_type <class 'numpy.bytes_'>
read_feec9e55-5765-4440-a414-0b624ac0d3aa run_id <class 'numpy.bytes_'>
read_ff126eff-7d31-48a5-b635-1637ed385fef pore_type <class 'numpy.bytes_'>
read_ff126eff-7d31-48a5-b635-1637ed385fef run_id <class 'numpy.bytes_'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type <class 'numpy.bytes_'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba run_id <class 'numpy.bytes_'>
```

but

```python3
for read in f:
    for i in f[read].attrs['pore_type']:
        print(read,'pore_type:', type(I))
```

gives

```
read_ff126eff-7d31-48a5-b635-1637ed385fef pore_type: <class 'int'>
read_ff126eff-7d31-48a5-b635-1637ed385fef pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type: <class 'int'>
```

weird

**Comment by Psy-Fer** [comment]
Apparently we have to do

```python3
print(read, i, j.decode('UTF-8'))
```

to get this:

```
read_fec54356-9a3a-42c3-9e8f-739513a3619b pore_type not_set
read_fec54356-9a3a-42c3-9e8f-739513a3619b run_id e7c896467265d9c5a774efee85e670ff7a21a05d
read_feec9e55-5765-4440-a414-0b624ac0d3aa pore_type not_set
read_feec9e55-5765-4440-a414-0b624ac0d3aa run_id e7c896467265d9c5a774efee85e670ff7a21a05d
read_ff126eff-7d31-48a5-b635-1637ed385fef pore_type not_set
read_ff126eff-7d31-48a5-b635-1637ed385fef run_id e7c896467265d9c5a774efee85e670ff7a21a05d
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba pore_type not_set
read_fff2915e-9a13-4da9-b9d2-cd616a36dfba run_id e7c896467265d9c5a774efee85e670ff7a21a05d
```

That will do the correct decoding of the numpy.bytes_ class

**Comment by Psy-Fer** [comment]
Not sure what the C equivalent here will be.

Not sure why I get different types when using an item() getter rather than a named get. If I tried to do a named get, I would not be able to see "note_set" at all, just random numbers. This has to be some kind of bug from the ONT side of things.

My guess is that slow5_tools is looking at the type of the value, and seeing `int` rather than some byte string, then comparing those values and seeing them as different, triggering the error. This information would be stored in the header once, as you would not expect multiple pore_types (at least not yet).

**Comment by hiruna72** [comment]
Hello @mbhall88,

Thank you very much for reporting this issue. The file you sent does not have an expected attribute (`file_type`) which is usually found at the root group. The file was misidentified as a single-fast5 file and that caused `f2s` to error out. The error message was saying something completely different. However, that helped us to discover another bug related to `pore_type`.

![Screenshot from 2022-09-26 16-12-07](https://user-images.githubusercontent.com/23216727/192208540-ddbb40d1-283e-4610-b718-f3fc3cfab604.png)

Could you please share any information on how this file was generated?

**Comment by mbhall88** [comment]
This sequencing run was done a few years ago - ~2019 I think. There's not really anything else I can think of that is out of the ordinary.... I thought that maybe I merged a bunch of single fast5s, but the file name makes me think not (I normally use the default prefix in the ont fast5 api singoe 2 multi tool, which renames them batch_0 etc.)

What other kind of info do you need?

**Comment by hasindu2008** [comment]
It seems like this is one of those files between when ONT did the transition from single to multi-fast5. This file structure is something in between real  multi-fast5 and single to multi-converted fast5. Do you have many datasets like this or is it only a few? We have to think about how we can go ahead in doing this in f2s without affecting the types of fast5 files it work with. Till then could you please use this [script](https://github.com/hasindu2008/slow5tools/blob/master/scripts/mixed-multi-fast5-to-blow5.sh`)? It is a script that I wrote to handle multi-fast5 generated using the ONT's `single_to_multi_fast5` when multiple run IDs are mixed up in the same file. I ran this script on your file and it worked. Make sure you have `multi_to_single_fast5`   that comes with ONT fast5 API, h5dump (apt-get install hdf5-tools), parallel (apt-get install parallel) and slow5tools in PATH.

**Comment by mbhall88** [comment]
I've got about 5/6 runs I think. I wouldn't worry about trying to support files like this if they're a weird transition/corner case. Gotta maintain your sanity!

I'll give that script a go. Thanks!

**Comment by hasindu2008** [comment]
Ohh there was a typo on this link and sorry I did not see the last 404 part until @hiruna72 told me, the link is https://github.com/hasindu2008/slow5tools/blob/master/scripts/mixed-multi-fast5-to-blow5.sh.

**Comment by hasindu2008** [comment]
@mbhall88 Did this script work?

**Comment by mbhall88** [comment]
I *think* so. Sorry, I haven't forgotten about this. I am running it on a collection of nanopore runs and it's taking a few days. Hopefully the jobs will finish over the weekend. I'll close this issue when/if they finish successfully if that's okay?

**Comment by hasindu2008** [comment]
Sure. No prob.

**Comment by mbhall88** [comment]
That script seems to have done the trick! Thanks a lot @hasindu2008
